global:
  scrape_interval: 15s # Frequent for real-time metrics
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "rules/alerting-rules.yml"

scrape_configs:
  - job_name: "order-service"
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ["order-service:80"]
